### ISSUE TITLE
Package throws errors when trying to build in 2020.2.5f1, Windows

### ISSUE THREAD

**Issue by BigHandInSky** [brunomikoski/UnityHistoryPanel#3]
`Library\PackageCache\com.brunomikoski.editorhistorypanel@1fcebab9bf\Scripts\Editor\HistoryPanelEditorWindow.cs(7,52): error CS0246: The type or namespace name 'EditorWindow' could not be found (are you missing a using directive or an assembly reference?)
`

`Library\PackageCache\com.brunomikoski.editorhistorypanel@1fcebab9bf\Scripts\Editor\HistoryPanelCore.cs(10,6): error CS0246: The type or namespace name 'InitializeOnLoadAttribute' could not be found (are you missing a using directive or an assembly reference?)
`

`Library\PackageCache\com.brunomikoski.editorhistorypanel@1fcebab9bf\Scripts\Editor\HistoryPanelCore.cs(10,6): error CS0246: The type or namespace name 'InitializeOnLoad' could not be found (are you missing a using directive or an assembly reference?)
`

`Library\PackageCache\com.brunomikoski.editorhistorypanel@1fcebab9bf\Scripts\Editor\HistoryPanelCore.cs(197,69): error CS0246: The type or namespace name 'PlayModeStateChange' could not be found (are you missing a using directive or an assembly reference?)
`

`Library\PackageCache\com.brunomikoski.editorhistorypanel@1fcebab9bf\Scripts\Editor\HistoryPanelEditorWindow.cs(73,17): error CS0246: The type or namespace name 'EditorApplication' could not be found (are you missing a using directive or an assembly reference?)
`

`Library\PackageCache\com.brunomikoski.editorhistorypanel@1fcebab9bf\Scripts\Editor\HistoryPanelEditorWindow.cs(234,10): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)
`

`Library\PackageCache\com.brunomikoski.editorhistorypanel@1fcebab9bf\Scripts\Editor\HistoryPanelEditorWindow.cs(234,10): error CS0246: The type or namespace name 'MenuItem' could not be found (are you missing a using directive or an assembly reference?)
`

I believe this just because the assembly definition is set to include Mac/Windows 64 bit, when it should only be including the Editor. Copying the source into my project and toggling those off let's me build ok.

**Comment by brunomikoski** [comment]
Thanks for the heads up! I will check later today!
